name: Deploy to Github Pages

on:
  push:
    branches: ["developer", "master", "release"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployments.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
      
      # 1. Validar primeiro (Se falhar aqui, o resto nem executa)
      - name: Validar sintaxe do HTML
        uses: htmlhint/action-htmlhint@v2
        with:
          pattern: 'index.html'

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Explorando o run  
        run: lsb_release -a && free -h

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
        
      - name: Deploy to github pages
        id: deployments
        uses: actions/deploy-pages@v4

      - name: Checar arquivos estáticos
        run: |
          ls -R
          echo "Todos os arquivos foram carregados no Runner!"