name: Deploy to Github Pages

on:
  push:
    branches: ["developer", "master", "release"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployments.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verificar Pasta src
        run: test -d src || (echo "Pasta src não encontrada!" && exit 1)

      - name: Verificar CSS
        run: test -f src/css/style.css || (echo "Arquivo src/css/style.css não encontrado!" && exit 1)

      - name: Executar Linter HTML
        run: npx htmlhint src/index.html

      - name: Validar Footer e Nome do Aluno
        run: |
          # Verifica se a tag footer existe e se o nome Lucas Martins está presente nela
          if grep -qzP "(?s)<footer.*Lucas Martins.*</footer>" src/index.html; then
            echo "Sucesso: O nome Lucas Martins foi encontrado dentro do footer!"
          else
            echo "ERRO: O nome 'Lucas Martins' não foi encontrado dentro da tag <footer>."
            echo "Certifique-se de que o nome está escrito corretamente no index.html"
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to github pages
        id: deployments
        uses: actions/deploy-pages@v4
      
      - name: Mensagem de Auditoria Final
        run: |
          echo "O código do aluno Lucas Martins foi auditado, está seguindo as normas corretas e está pronto para o deploy!"