name: Deploy to Github Pages

on:
  push:
    branches: ["developer", "master", "release"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployments.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verificar Pasta src
        run: test -d src || (echo "Pasta src não encontrada!" && exit 1)

      - name: Verificar CSS
        run: test -f src/css/style.css || (echo "Arquivo src/css/style.css não encontrado!" && exit 1)

      # - name: Linting HTML
      #   uses: htmlhint/action@v2
      #   with:
      #     target_pattern: 'src/index.html'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to github pages
        id: deployments
        uses: actions/deploy-pages@v4